#!/bin/bash
DISTRO=$(cat /etc/os-release | grep "^NAME" | cut -d '=' -f 2 | cut -d '"' -f 2)

if ! [[ -d /home/fusion809/.i3 ]]; then
    printf "i3 directory not found\n" ; exit
fi

if [[ $DISTRO == openSUSE* ]]; then
    git -C /home/fusion809/.i3 checkout opensuse
elif [[ $DISTRO == Arch* ]]; then
    git -C /home/fusion809/.i3 checkout archlinux
elif [[ $DISTRO == Debian* ]]; then
    git -C /home/fusion809/.i3 checkout master
elif [[ $DISTRO == Gentoo* ]]; then
    git -C /home/fusion809/.i3 checkout gentoo
else
    printf "You do not seem to be using Arch, Debian, Gentoo or openSUSE\n"
fi
